version: 0.2

phases:
  pre_build:
    commands:
      - echo logging to ECR
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPO_URI="626505363333.dkr.ecr.ap-south-1.amazonaws.com/dockerdev-repo"
      - echo ${CODEBUILD_BUILD_NUMBER}
      - IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}

  build:
    commands:
      - echo build started on `date`
      - echo BUILD NO = ${IMAGE_TAG}
      - docker build -t ${REPO_URI}:${IMAGE_TAG} --build-arg BUILD_NO=${IMAGE_TAG} .
      - docker tag ${REPO_URI}:${IMAGE_TAG} ${REPO_URI}:latest .

  post_build:
    commands:
      - echo Build Completed on `date`
      - echo Publishing the Docker images ...
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - docker push ${REPO_URI}:latest
      - printf '[{"name":"web-container","imageUri":"%s"}]' ${REPO_URI}:${IMAGE_TAG} > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
